### ISSUE TITLE
Decouple and remove duplication from rbm.py for the RBM initialization and sampling procedures

### ISSUE THREAD

**Issue by abhishekabhishek** [ezeeEric/DiVAE#7]

**Comment by abhishekabhishek** [comment]
Is there a way to separate the RBM implementation and the sampling methods ? Would be helpful in case we want to try out different techniques (PA, PCD etc.)

**Comment by ezeeEric** [comment]
That's been on my list since a while and definitely necessary. The CD sampler is baked in weirdly to the RBM class, lots of unnecessary interdependencies. It might be worth just starting with these from scratch.
